// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace ServiceCarTracker
{
	public partial class ViewControllerOil : NSViewController
	{
		public ViewControllerOil (IntPtr handle) : base (handle)
		{
		}
	}
}
