// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace ServiceCarTracker
{
	public partial class ViewControllerDashboard : NSViewController
	{
		public ViewControllerDashboard (IntPtr handle) : base (handle)
		{
		}
	}
}
