// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace ServiceCarTracker
{
	public partial class ViewControllerServiceAndExpenses : NSViewController
	{
		public ViewControllerServiceAndExpenses (IntPtr handle) : base (handle)
		{
		}
	}
}
